version: "3.8"
services:
    postgres:
        build: .
        restart: always
        image: postgres:12
        ports:
            - "5432:5432"
        environment: 
            - DEBUG=false

            - DB_USER=
            - DB_PASS=
            - DB_NAME=
            - DB_TEMPLATE=

            - DB_EXTENSION=

            - REPLICATION_MODE=
            - REPLICATION_USER=
            - REPLICATION_PASS=
            - REPLICATION_SSLMODE=
        